stack: tero/elasticsearch
version: 0.1.0
description: Elasticsearch
expose: elasticsearch
variables:
  instances:
    type: integer
    from:
      prompt: How many instances for Elasticsearch?

  mem_limit:
    type: integer
    default: 2048
    from:
      prompt: Memory limit for Elasticsearch (in megabytes).

  jvm_limit:
    type: integer
    from:
      evaluate: ${mem_limit} * 0.8

  affinity:
    type: string
    required: false
    from:
      prompt: Affinity rule for Elasticsearch

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    instances: {{ instances }}
    stateful: true
    mem_limit: "{{ mem_limit }}m"
    environment:
      cluster.name: graylog
      network.host: _ethwe_
      discovery.zen.ping.unicast.hosts: elasticsearch
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms{{ jvm_limit }}m -Xmx{{ jvm_limit }}m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    affinity:
      # {% if affinity %}
      - {{ affinity }}
      # {% endif %}

volumes:
  elasticsearch-data:
    external:
      name: elasticsearch-data
